### ISSUE TITLE
In need of help

### ISSUE THREAD

**Issue by fobos531** [eoli3n/dotfiles#1]
Hello, I couldn't find an email or something to write to you privately so I'm doing it here. I saw your setup when you posted on /r/unixporn and I think it's beautiful. I was so impressed with it that I decided to set it up like you have it. So I went to your dotfiles page, followed the instructions in readme, installed the packages (pac and aur) and created all the files and folders, structured like yours. I also made path, interface changes where I thought they were needed so it would work on my system. I then rebooted and it didn't turn out as expected. Things are clearly not working and need fixing. That's why I'm asking for your help. I'll post my dotfiles, installed packages, paste a screenshot of how it looks right now for me.

Installed packages: http://pastebin.com/uqehZ7Zh
Screenshot: http://1.1m.yt/teLoHq1.png (no changes have been done, except adding pkg.sh where it belongs and chmodding it)
Dotfiles (there are some rudimentary config files, feel free to ignore them; if I'm missing any, tell me): https://github.com/fobos531/dotfiles-testing

If you choose to help me, I'll be very thankful. If not, no problem, I understand you have other things to do :)

Thanks in advance.

**Comment by eoli3n** [comment]
Hi,

Some point I see
- your shell is bash, you need zsh to get agnoster theme : run this to set it as default shell for your user
```    
chsh -s /usr/bin/zsh
```
- you missed to install pkg.sh script in .config/polybar/

- i see that i missed a dependancy , please install
```
pacaur -S cower
```
- neofetch cmd is an alias with some options in .zshrc, it will works with zsh, see > https://github.com/eoli3n/dotfiles/blob/master/.zshrc#L29

- to get chrome dark theme, please go to graphical configuration and click "Use GTK+ theme"

- another thing is that if force systray to be at top left corner, that's why you have a strange red icon here. Please change "tray-position = left" to "tray-position = right" in .config/polybar/config

- you don't have the bottom polybar, is it normal ?

Hope this helps.

**Comment by eoli3n** [comment]
Ah, and to get github notification, you need to create a "github personnal access token" and set the var in your .zshrc. https://github.com/blog/1509-personal-api-tokens
I warn you that you need to keep it secret.

To keep it secret, in .zshrc, i include .zshrc_node, which is not uploaded to github.
The var to set is 
```
export GITHUB_API_TOKEN=************************************
```

Second way is to simply disable the "github" module in the module-right var in .config/polybar/config

**Comment by eoli3n** [comment]
Please also run
```
sudo pacman -S lxappearance
```
and read 

https://github.com/eoli3n/dotfiles#gtk-and-qt

**Comment by fobos531** [comment]
Thank for the replies. Here are the updates:

1. changing shells went fine. Only thing bothering me a bit is that I have this "master" addition from github in my terminal, like this: http://4.1m.yt/siKe9WE.png What exactly do I need to edit to remove this?

2. installing pkg.sh went fine
3. i already had cower (it was a dependency for pacaur)
4. you're correct about neofetch, works fine when running in zsh, except when I shift the focus to another window (chrome for example), archlinux.png disappears in the terminal and doesn't reappear upon returning focus to the terminal
5. polybar: no, it's not normal that I don't have the bottom bar. are my dotfiles misconfigured? 
6. lxappearance and chrome: done, thanks for that
7. github tokens: done, will see about disabling it.
8. also, regarding interfacelift, are you still using it? I see you removed it from your dotfiles. I tried tinkering with your other repo (interfaceliftdownloader) and will see now whether it'll work for me.
9. i want to get rid of albert (i'll probably replace it with rofi or sth.): is simply "pacaur -Rs albert" and removing it from .xprofile enough or do I need to do something else? Cause I did exactly that and it still appears.

i3 still returns errors when executing:
error log: http://pastebin.com/7T1SQSkk
updated config (will probably tinker with it a little bit more later): http://pastebin.com/q4LavaTg

**Comment by eoli3n** [comment]
1° Maybe you can comment that line in .oh-my-zsh/themes/agnoster.zsh-theme
https://gist.github.com/agnoster/3712874#file-agnoster-zsh-theme-L130
OR
Changing theme with one of theses
- https://github.com/robbyrussell/oh-my-zsh/wiki/themes
- https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes

4° I have the same issue, maybe that's a compton or i3 problem...

5° please try to run ``polybar bottom`` in a shell to see if there is any error. Polybar need custom configuration...

7° disable the module in .config/polybar/config only if you don't want it

8° the interfacelift repo needs upgrade, i will change it and tell you when it's ok to test

9° maybe, if you didn't reboot, you need to "pkill albert" too.

For your i3 errors, i can't setup everything for you, you need to read the error log !

Some points : 
```
10.01.2017 11:58:34 - ERROR: CONFIG: Line  18: bindsym Mod4+d exec --no-startup-id j4-dmenu-desktop --dmenu="dmenu -fn 'hack-10' -h 20 -nb '#202020'
10.01.2017 11:58:34 - ERROR: CONFIG: Line  19: -nf '#FFFFFF' -sf '#dc322f' -sb '#202020' -p '>' -b -w 400 -q -o 0.9"
```
i3 read it as two separated lines... these are a single one...

```
10.01.2017 11:58:34 - ERROR: CONFIG: Line 151: bindsym Mod4+Control+Up exec "~/dev/git/lyricsdownloader/graphicalrapgenius.sh"
10.01.2017 11:58:34 - ERROR: CONFIG: Line 152: bindsym Mod4+Control+Prior exec "cd ~/dev/git/interfaceliftdownloader/ ; ./interfacelift.sh -c
10.01.2017 11:58:34 - ERROR: CONFIG: Line 153: ./wallpaper.conf"
10.01.2017 11:58:34 - ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^
10.01.2017 11:58:34 - ERROR: CONFIG: Line 154: bindsym Mod4+Control+Next exec "~/dev/git/interfaceliftdownloader/interfacelift.sh -sc
10.01.2017 11:58:34 - ERROR: CONFIG: Line 155: ~/dev/git/interfaceliftdownloader/wallpaper.conf"
[...]
10.01.2017 11:58:34 - ERROR: CONFIG: Line 153: ./wallpaper.conf"
10.01.2017 11:58:34 - ERROR: CONFIG: Line 154: bindsym Mod4+Control+Next exec "~/dev/git/interfaceliftdownloader/interfacelift.sh -sc
10.01.2017 11:58:34 - ERROR: CONFIG: Line 155: ~/dev/git/interfaceliftdownloader/wallpaper.conf"
```

Thoses paths ``~/dev/git/interfaceliftdownloader/`` needs to be existant.

You need to understand that my confs are **my** conf, so you need to adapt it a little bit.

Please read

- how to configure .i3/config > https://i3wm.org/docs/userguide.html
- how to configure .config/polybar/config > https://github.com/jaagr/polybar/wiki
- how to configure zsh > https://wiki.archlinux.org/index.php/zsh
- your i3 error log file, to understand what happen.

This is not a ``working out of the box`` configuration, but a template which need to be adapt.

**Comment by fobos531** [comment]
Alright, I configured it to the point where I like it.

Another minor issue I'm experiencing: Powerline fonts ("x" mark etc.) for agnoster theme aren't being rendered properly. I installed them both to ~/.fonts and the directory that was originally in install.sh and it still isn't being rendered properly.  Am I missing somehting?

**Comment by eoli3n** [comment]
I installed fonts with pacman packages, and not user side, so i can't help you on this point.
Maybe try to run this, to update font cache
```
fc-cache -f
```

You need to set a powerline patched font in your .Xressources, i use ``hack`` which is nativly powerline ready.
Or try one of these > https://github.com/powerline/fonts
