### ISSUE TITLE
Vagrant - Muti-machine

### ISSUE THREAD

**Issue by ghost** [eoli3n/dotfiles#5]
Salut,

Il y a la possibilité de faire plusieurs machines dans un Vagrantfile :
- https://www.vagrantup.com/docs/multi-machine/

Si tu veux, je peux le faire, tu peux m'assigner ce ticket.

**Comment by eoli3n** [comment]
Bonjour,
Je ne comprend pas trop l’intérêt vu que les machines en question ne sont pas censées fonctionner simultanément/ensemble, il n'y a pas d'interaction entre elles.
Les vagrantfile sont là uniquement pour laisser l'utilisateur tester manuellement l'une ou l'autre des configurations.
