### ISSUE TITLE
top of the icon has been covered 

### ISSUE THREAD

**Issue by jidibinlin** [eoli3n/dotfiles#6]
* Hi you config is very nice. I just install the config of polybar through copy the **config launch.sh and pkg.sh** in the branch of [zsh-agnoster-solarized](https://github.com/eoli3n/dotfiles/tree/zsh-agnoster-solarized) to my ~/.confg/polybar.
* And I installed the **ttf-font-awesome ttf-unifont and ttf-font-icon**
* But now the edge of the screen cover the icon on the bar just like this.

![polybar2](https://user-images.githubusercontent.com/38578679/66711613-b30dae00-edc1-11e9-807c-c4b33f924c2e.png)
**you should zoom it to see it clealy**
* hope you can help me solved it. Thank you!

**Comment by eoli3n** [comment]
Hi, 

You need to install https://www.archlinux.org/packages/extra/any/ttf-hack/
Then
https://github.com/eoli3n/dotfiles/blob/master/roles/polybar/templates/config.j2#L74
in your polybar config file.
Or just change font and size here.

Hope this help.
