### ISSUE TITLE
Some font can't recognize /

### ISSUE THREAD

**Issue by tmpm697** [eoli3n/dotfiles#7]
My font can't recognize:
```
"format-ethernet": "<span foreground='#929292'></span> wired",
and
"format": "<span foreground='#929292'></span> vpn",
```
Can you help to give more general icons instead? It recognize others ok.

**Comment by eoli3n** [comment]
I use Font Awesome 5 : https://fontawesome.com/v5.15/icons?d=gallery&m=free
